runtime: nodejs16
service: default
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: public/\1
    upload: public/(.*\..+)$
    # catch all handler to index.html
  - url: /.*
    static_files: public/index.html
    upload: public/index.html