name: Deploy to Google App Engine
on:
  push:
    branches:
      - development
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
      with:

        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.gcp_credentials }}
        deliverables: app.yml api.yml dispatch.yml